name: nucleic_acid
description: This is a package for nucleic acid analysis support. This package is made for scientists.
version: 0.0.6
repository: https://github.com/MasahideMori-SimpleAppli/nucleic_acid

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
