name: nucleic_acid
description: A set of utilities and dictionaries to aid in nucleic acid analysis.
version: 0.0.1
repository: https://github.com/MasahideMori-SimpleAppli/nucleic_acid

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
