/// Some information was created with reference to:
/// https://www.ddbj.nig.ac.jp/ddbj/code.html
/// https://creativecommons.org/licenses/by/4.0/deed.ja
class FAminoAcid {
  static const Map<String, String> fullToThree = {
    'Alanine': 'Ala',
    'Arginine': 'Arg',
    'Asparagine': 'Asn',
    'Aspartic acid': 'Asp',
    'Cysteine': 'Cys',
    'Glutamic acid': 'Glu',
    'Glutamine': 'Gln',
    'Glycine': 'Gly',
    'Histidine': 'His',
    'Isoleucine': 'Ile',
    'Leucine': 'Leu',
    'Lysine': 'Lys',
    'Methionine': 'Met',
    'Phenylalanine': 'Phe',
    'Proline': 'Pro',
    'Serine': 'Ser',
    'Threonine': 'Thr',
    'Tryptophan': 'Trp',
    'Tyrosine': 'Tyr',
    'Valine': 'Val',
    // 追加のアミノ酸やor指定など
    'Selenocysteine': 'Sec',
    'Aspartic acid or Asparagine': 'Asx',
    'Glutamic acid or Glutamine': 'Glx',
    'Any amino acid': 'Xaa',
    'Leucine or Isoleucine': 'Xle',
    // 終止コドン
    'termination codon': 'TERM'
  };

  static const Map<String, String> fullToOne = {
    'Alanine': 'A',
    'Arginine': 'R',
    'Asparagine': 'N',
    'Aspartic acid': 'D',
    'Cysteine': 'C',
    'Glutamic acid': 'E',
    'Glutamine': 'Q',
    'Glycine': 'G',
    'Histidine': 'H',
    'Isoleucine': 'I',
    'Leucine': 'L',
    'Lysine': 'K',
    'Methionine': 'M',
    'Phenylalanine': 'F',
    'Proline': 'P',
    'Serine': 'S',
    'Threonine': 'T',
    'Tryptophan': 'W',
    'Tyrosine': 'Y',
    'Valine': 'V',
    // 追加のアミノ酸やor指定など
    'Selenocysteine': 'U',
    'Aspartic acid or Asparagine': 'B',
    'Glutamic acid or Glutamine': 'Z',
    'Any amino acid': 'X',
    'Leucine or Isoleucine': 'J',
  };

  static const Map<String, String> threeToFull = {
    'Ala': 'Alanine',
    'Arg': 'Arginine',
    'Asn': 'Asparagine',
    'Asp': 'Aspartic acid',
    'Cys': 'Cysteine',
    'Glu': 'Glutamic acid',
    'Gln': 'Glutamine',
    'Gly': 'Glycine',
    'His': 'Histidine',
    'Ile': 'Isoleucine',
    'Leu': 'Leucine',
    'Lys': 'Lysine',
    'Met': 'Methionine',
    'Phe': 'Phenylalanine',
    'Pro': 'Proline',
    'Ser': 'Serine',
    'Thr': 'Threonine',
    'Trp': 'Tryptophan',
    'Tyr': 'Tyrosine',
    'Val': 'Valine',
    // 追加のアミノ酸やor指定など
    'Sec': 'Selenocysteine',
    'Asx': 'Aspartic acid or Asparagine',
    'Glx': 'Glutamic acid or Glutamine',
    'Xaa': 'Any amino acid',
    'Xle': 'Leucine or Isoleucine',
    // 終止コドン
    'TERM': 'termination codon'
  };

  static const Map<String, String> threeToOne = {
    'Ala': 'A',
    'Arg': 'R',
    'Asn': 'N',
    'Asp': 'D',
    'Cys': 'C',
    'Glu': 'E',
    'Gln': 'Q',
    'Gly': 'G',
    'His': 'H',
    'Ile': 'I',
    'Leu': 'L',
    'Lys': 'K',
    'Met': 'M',
    'Phe': 'F',
    'Pro': 'P',
    'Ser': 'S',
    'Thr': 'T',
    'Trp': 'W',
    'Tyr': 'Y',
    'Val': 'V',
    // 追加のアミノ酸やor指定など
    'Sec': 'U',
    'Asx': 'B',
    'Glx': 'Z',
    'Xaa': 'X',
    'Xle': 'J',
  };

  static const Map<String, String> oneToFull = {
    'A': 'Alanine',
    'R': 'Arginine',
    'N': 'Asparagine',
    'D': 'Aspartic acid',
    'C': 'Cysteine',
    'E': 'Glutamic acid',
    'Q': 'Glutamine',
    'G': 'Glycine',
    'H': 'Histidine',
    'I': 'Isoleucine',
    'L': 'Leucine',
    'K': 'Lysine',
    'M': 'Methionine',
    'F': 'Phenylalanine',
    'P': 'Proline',
    'S': 'Serine',
    'T': 'Threonine',
    'W': 'Tryptophan',
    'Y': 'Tyrosine',
    'V': 'Valine',
    // 追加のアミノ酸やor指定など
    'U': 'Selenocysteine',
    'B': 'Aspartic acid or Asparagine',
    'Z': 'Glutamic acid or Glutamine',
    'X': 'Any amino acid',
    'J': 'Leucine or Isoleucine',
  };

  static const Map<String, String> oneToThree = {
    'A': 'Ala',
    'R': 'Arg',
    'N': 'Asn',
    'D': 'Asp',
    'C': 'Cys',
    'E': 'Glu',
    'Q': 'Gln',
    'G': 'Gly',
    'H': 'His',
    'I': 'Ile',
    'L': 'Leu',
    'K': 'Lys',
    'M': 'Met',
    'F': 'Phe',
    'P': 'Pro',
    'S': 'Ser',
    'T': 'Thr',
    'W': 'Trp',
    'Y': 'Tyr',
    'V': 'Val',
    // 追加のアミノ酸やor指定など
    'U': 'Sec',
    'B': 'Asx',
    'Z': 'Glx',
    'X': 'Xaa',
    'J': 'Xle',
  };

  static const Map<String, String> enFullToJaFull = {
    'Alanine': 'アラニン',
    'Arginine': 'アルギニン',
    'Asparagine': 'アスパラギン',
    'Aspartic acid': 'アスパラギン酸',
    'Cysteine': 'システイン',
    'Glutamic acid': 'グルタミン酸',
    'Glutamine': 'グルタミン',
    'Glycine': 'グリシン',
    'Histidine': 'ヒスチジン',
    'Isoleucine': 'イソロイシン',
    'Leucine': 'ロイシン',
    'Lysine': 'リジン',
    'Methionine': 'メチオニン',
    'Phenylalanine': 'フェニルアラニン',
    'Proline': 'プロリン',
    'Serine': 'セリン',
    'Threonine': 'スレオニン',
    'Tryptophan': 'トリプトファン',
    'Tyrosine': 'チロシン',
    'Valine': 'バリン',
    // 追加のアミノ酸やor指定など
    'Selenocysteine': 'セレノシステイン',
    'Aspartic acid or Asparagine': 'アスパラギン酸またはアスパラギン',
    'Glutamic acid or Glutamine': 'グルタミン酸またはグルタミン',
    'Any amino acid': '任意のアミノ酸',
    'Leucine or Isoleucine': 'ロイシンまたはイソロイシン',
    // 終止コドン
    'termination codon': '終止コドン'
  };

  static const Map<String, String> jaFullToEnFull = {
    'アラニン': 'Alanine',
    'アルギニン': 'Arginine',
    'アスパラギン': 'Asparagine',
    'アスパラギン酸': 'Aspartic acid',
    'システイン': 'Cysteine',
    'グルタミン酸': 'Glutamic acid',
    'グルタミン': 'Glutamine',
    'グリシン': 'Glycine',
    'ヒスチジン': 'Histidine',
    'イソロイシン': 'Isoleucine',
    'ロイシン': 'Leucine',
    'リジン': 'Lysine',
    'メチオニン': 'Methionine',
    'フェニルアラニン': 'Phenylalanine',
    'プロリン': 'Proline',
    'セリン': 'Serine',
    'スレオニン': 'Threonine',
    'トリプトファン': 'Tryptophan',
    'チロシン': 'Tyrosine',
    'バリン': 'Valine',
    // 追加のアミノ酸やor指定など
    'セレノシステイン': 'Selenocysteine',
    'アスパラギン酸またはアスパラギン': 'Aspartic acid or Asparagine',
    'グルタミン酸またはグルタミン': 'Glutamic acid or Glutamine',
    '任意のアミノ酸': 'Any amino acid',
    'ロイシンまたはイソロイシン': 'Leucine or Isoleucine',
    '終止コドン': 'termination codon'
  };
}
